### ISSUE TITLE
[ Architecture ] Persistence Package 추가

### ISSUE THREAD

**Issue by onemoongit** [mash-up-kr/09-Back#13]
공부를 하다보니 Repository에 대한 관리를 Persistence 라는 패키지에서 하는게 깔끔할 것 같습니다.

현재 Domain에 있는 Repository 들을 Persistence 라는 패키지를 만들어 분류를 나누고 이동해주세요

읽었으면 이모티콘이나 코멘트 남겨주세요!

**Comment by SujiKim6** [comment]
table수정하고 persistence라는 패키지에 repository넣어서 push 할게요

**Comment by onemoongit** [comment]
YES 
/Persistence/Item
/Persistence/User
/Persistence/Category

@SujiKim6

**Comment by SujiKim6** [comment]
그럼 탭들은 다 Item에 넣겠습니다~~
@onemoongit
